version: '3.8'

services:
  web:
    build: .
    container_name: cerbose-react
    ports:
      - '5173:5173'
    develop:
      watch:
        - action: sync
          path: .
          target: /app
        - action: rebuild
          path: ./package.json